project_id = "ihthnipyfppatlmaajvm"

[functions.create-admin-user]
verify_jwt = false

[functions.delete-admin-user]
verify_jwt = false

[functions.update-last-login]
verify_jwt = false

[functions.fotofacil-create-order]
verify_jwt = false

[functions.fotofacil-webhook]
verify_jwt = false

[functions.fotofacil-validate-delivery]
verify_jwt = false
