project_id = "ihthnipyfppatlmaajvm"

[functions.fotofacil-lookup-orders]
verify_jwt = false

[functions.fotofacil-check-payment]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.delete-admin-user]
verify_jwt = false

[functions.update-last-login]
verify_jwt = false

[functions.fotofacil-create-order]
verify_jwt = false

[functions.fotofacil-webhook]
verify_jwt = false

[functions.fotofacil-validate-delivery]
verify_jwt = false

[functions.gcs-upload]
verify_jwt = false

[functions.gcs-signed-url]
verify_jwt = false

[functions.gcs-delete]
verify_jwt = false

[functions.gcs-upload-watermark]
verify_jwt = false
